resources.load([
  "./images/blue_bird.png",
  "./images/red_bird.png",
  "./images/yellow_bird.png",
  "./images/pipe/ground.png",
  "./images/pipe/top.png",
  "./images/pipe/small-cloud.png"
])
resources.onReady(main)
